# Generated by Django 5.0.6 on 2024-07-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='test_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.test'),
        ),
    ]
