# Generated by Django 5.0.6 on 2024-07-03 04:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_testattempt_useranswer_test_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Question'),
        ),
    ]
