# Generated by Django 5.0.6 on 2024-07-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
