# Generated by Django 5.0.6 on 2024-07-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_questiongroup_question_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
    ]
