# Generated by Django 5.0.6 on 2024-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='link_image',
            field=models.ImageField(default='links/personal_profile.jpg', upload_to='links'),
        ),
    ]
