# Generated by Django 5.0.6 on 2024-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
