# Generated by Django 5.0.6 on 2024-07-01 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 1, 21, 31, 3, 435905, tzinfo=datetime.timezone.utc)),
        ),
    ]
