# Generated by Django 5.0.6 on 2024-07-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='other_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, default='https://x.com/', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/', null=True),
        ),
    ]
