# Generated by Django 5.0.6 on 2024-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='I did not write a bio yet', max_length=300),
        ),
    ]
