# Generated by Django 5.0.6 on 2024-06-28 17:48

import datetime
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("tutor", "0002_alter_tutoring_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoring",
            name="category",
            field=models.CharField(
                choices=[
                    ("topik", "Topik"),
                    ("daily", "Daily"),
                    ("kiip", "KIIP"),
                    ("visa", "Visa"),
                    ("other", "other"),
                ],
                default="topik",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tutoring",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 28, 17, 48, 36, 61918, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="tutoring",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "submitted"),
                    ("in_review", "in_review"),
                    ("posted", "posted"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tutoring",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
