# Generated by Django 5.0.6 on 2024-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0003_tutoring_category_tutoring_date_tutoring_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutoring",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
