# Generated by Django 5.0.6 on 2024-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0004_alter_tutoring_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoring",
            name="short_description",
            field=models.CharField(
                default="No short describtion provided, you can read full description",
                max_length=200,
                verbose_name="Describe shortly what it is about",
            ),
        ),
    ]
