# Generated by Django 5.0.6 on 2024-07-01 21:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_tutoring_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoring',
            options={'ordering': ('-date', 'title')},
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 1, 21, 31, 3, 435905, tzinfo=datetime.timezone.utc))),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_review', to=settings.AUTH_USER_MODEL)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tutor.tutoring')),
            ],
        ),
    ]
