# Generated by Django 5.0.6 on 2024-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_alter_tutoring_options_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
