# Generated by Django 5.0.6 on 2024-07-01 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_rating_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
        migrations.AlterModelOptions(
            name='tutoring',
            options={},
        ),
    ]
