# Generated by Django 5.0.6 on 2024-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_savedtutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoring',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
