# Generated by Django 5.0.6 on 2024-05-25 05:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_rename_topiccontent_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicAnswer',
            new_name='Answer',
        ),
    ]
