# Generated by Django 5.0.6 on 2024-06-04 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_upvoteranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
