# Generated by Django 5.0.6 on 2024-06-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_topic_topic_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
