# Generated by Django 5.0.6 on 2024-06-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_topic_topic_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_category',
            field=models.CharField(choices=[('Topik', 'Topik'), ('KIIP', 'KIIP'), ('Daily', 'Daily'), ('Other', 'Other')], default='Topik', max_length=15),
        ),
    ]
