# Generated by Django 5.0.6 on 2024-06-14 20:41

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
