# Generated by Django 5.0.6 on 2024-06-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0011_topic_additional_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_hashtag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
