# Generated by Django 5.0.6 on 2024-06-30 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_alter_topic_topic_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='additional_text',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_hashtag',
        ),
    ]
