# Generated by Django 5.0.6 on 2024-07-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_remove_topic_additional_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
