# Generated by Django 5.0.6 on 2024-07-05 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='podcast_audios')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('length', models.FloatField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('audio_uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_podcasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='podcasts.podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_podcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'podcast')},
            },
        ),
    ]
