# Generated by Django 5.0.6 on 2024-06-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='podcast_audios')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('length', models.FloatField(blank=True)),
                ('audio_uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
