# Generated by Django 5.0.6 on 2024-07-05 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_saved_podcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_podcasts',
            name='date_saved',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 3, 53, 25, 754475, tzinfo=datetime.timezone.utc)),
        ),
    ]
