# Generated by Django 5.0.6 on 2024-07-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_saved_podcasts_date_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_podcasts',
            name='date_saved',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
