# Generated by Django 5.0.6 on 2024-07-05 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_saved_podcasts_date_saved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_podcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='podcasts.podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_podcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'podcast')},
            },
        ),
        migrations.DeleteModel(
            name='Saved_podcasts',
        ),
    ]
