# Generated by Django 5.0.6 on 2024-06-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='book.bookcart'),
        ),
    ]
