# Generated by Django 5.0.6 on 2024-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_date_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
